# Generated by Django 5.2.11 on 2026-02-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certification_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
